apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: dfg
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-844679e5-85ca-4460-9a15-47edbbc97c0e
      eventName: github-844679e5-85ca-4460-9a15-47edbbc97c0e
      eventSourceName: dfg
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - release
            type: string
  triggers:
    - template:
        name: dfg
        conditions: github-844679e5-85ca-4460-9a15-47edbbc97c0e
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: dfg-dfg-
              spec:
                workflowTemplateRef:
                  name: argo-hub.ci-simple.0.0.1
          parameters: []
