apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  labels:
    label: true
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/andrii-codefresh/argocd-example-apps.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-production.yaml
        - values.yaml
  destination:
    name: in-cluster
    namespace: helm-guestbook
  syncPolicy:
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
